{% set name = "lcio" %}
{% set tag_version = "02-14-02" %}
{% set major, minor, patch = tag_version.split("-") %}

package:
  name: {{ name|lower }}
  version: {{ major.lstrip("0") or "0" }}.{{ minor.lstrip("0") or "0" }}.{{ patch.lstrip("0") or "0" }}

source:
  url: https://github.com/iLCSoft/LCIO/archive/v{{ tag_version }}.tar.gz
  sha256: e64f4bf932edf6d6cdaf0162e5104f8fbf3e5fd9737c7a080c48859009621919

build:
  number: 0
  skip: True  # [win]

# Specifying `compiler('cxx')` as a top-level build requirements to force
# conda-smithy to generate the correct build matrix.
requirements:
  build:
    - {{ compiler('cxx') }}


outputs:
  - name: lcio
    version: {{ version }}
    build:
      script: $RECIPE_DIR/build_lcio.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
      host:
        - root_base
        - root-binaries
        - zlib

about:
  home: https://github.com/iLCSoft/LCIO/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A persistency framework and event data model for linear collider detector studies'


  description: |
    A common persistency format and event data model allows to easily share
    results and compare reconstruction algorithms. LCIO is used by almost
    all groups involved in linear collider detector studies and thus has become a de facto standard.
  doc_url: https://ilcsoft.desy.de/LCIO/current/doc/doxygen_api/html/
  dev_url: https://github.com/iLCSoft/LCIO/

extra:
  recipe-maintainers:
    - petricm
